version: '3.8'

services:
  mysql:
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=vtc
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"

  your-application:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-application-image
    ports:
      - "8181:8181"
    depends_on:
      - mysql